name: Test PHP simple

on: push

jobs:
  dire-bonjour:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bonjour !"

  test-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Vérifier la version PHP
        run: php -v

      - name: Lancer index.php (CLI)
        run: php index.php
    
      - name: Installer dépendances
        run: composer install --no-interaction --prefer-dist

      - name: Fix permissions
        run: chmod -R +x vendor/bin

      - name: Lancer les tests
        run: composer run test