name: Test PHP simple

on: push

jobs:
  dire-bonjour:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bonjour !"

  test-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Installer dépendances
        run: composer install --no-interaction --prefer-dist

      - name: Debug arborescence
        run: ls -R

      - name: Lancer PHPUnit directement
        run: php vendor/bin/phpunit --testdox --display-errors